/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.rossmci;


/**
 *
 * @author Ross Mcinerney
 */
public class LinkedQueueFrame extends javax.swing.JFrame
{
 
	MergingTwoSortedQueues mergingTwoSortedQueues;
	private Queue first= new LinkedQueue();

	/**
	 * Creates new form linkedQueuesjframe
	 */
	public LinkedQueueFrame()
	{
		initComponents();
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        inputPanel = new javax.swing.JPanel();
        enterWordLabel = new javax.swing.JLabel();
        inputjTextField = new javax.swing.JTextField();
        outputjPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        ButtonjPanel = new javax.swing.JPanel();
        Q1jToggleButton = new javax.swing.JToggleButton();
        Q2jToggleButton = new javax.swing.JToggleButton();
        Q3jToggleButton = new javax.swing.JToggleButton();
        ExitjToggleButton4 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Queues");

        enterWordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        enterWordLabel.setText("Enter Word (IN Caps)");

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(enterWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputjTextField)
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterWordLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane1.setViewportView(outputTextArea);

        javax.swing.GroupLayout outputjPanelLayout = new javax.swing.GroupLayout(outputjPanel);
        outputjPanel.setLayout(outputjPanelLayout);
        outputjPanelLayout.setHorizontalGroup(
            outputjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        outputjPanelLayout.setVerticalGroup(
            outputjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputjPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );

        Q1jToggleButton.setText("Queue1");
        Q1jToggleButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Q1jToggleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Q1jToggleButtonActionPerformed(evt);
            }
        });

        Q2jToggleButton.setText("Queue2");
        Q2jToggleButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Q2jToggleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Q2jToggleButtonActionPerformed(evt);
            }
        });

        Q3jToggleButton.setText("Queue3");
        Q3jToggleButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Q3jToggleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Q3jToggleButtonActionPerformed(evt);
            }
        });

        ExitjToggleButton4.setText("Exit");
        ExitjToggleButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout ButtonjPanelLayout = new javax.swing.GroupLayout(ButtonjPanel);
        ButtonjPanel.setLayout(ButtonjPanelLayout);
        ButtonjPanelLayout.setHorizontalGroup(
            ButtonjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonjPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Q1jToggleButton)
                .addGap(51, 51, 51)
                .addGroup(ButtonjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExitjToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Q2jToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(Q3jToggleButton)
                .addContainerGap())
        );

        ButtonjPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Q1jToggleButton, Q2jToggleButton, Q3jToggleButton});

        ButtonjPanelLayout.setVerticalGroup(
            ButtonjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1jToggleButton)
                    .addComponent(Q2jToggleButton)
                    .addComponent(Q3jToggleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(ExitjToggleButton4)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(outputjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ButtonjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Q1jToggleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Q1jToggleButtonActionPerformed
    {//GEN-HEADEREND:event_Q1jToggleButtonActionPerformed

//		mergingTwoSortedQueues.first.append(inputjTextField.getText());
//		inputjTextField.setText("");
//		System.out.println("1"+queue1);
    }//GEN-LAST:event_Q1jToggleButtonActionPerformed

    private void Q2jToggleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Q2jToggleButtonActionPerformed
    {//GEN-HEADEREND:event_Q2jToggleButtonActionPerformed
//		queue2.add(inputjTextField.getText());
//		System.out.println("2"+queue2);
//		inputjTextField.setText("");
    }//GEN-LAST:event_Q2jToggleButtonActionPerformed

    private void Q3jToggleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Q3jToggleButtonActionPerformed
    {//GEN-HEADEREND:event_Q3jToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q3jToggleButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(LinkedQueueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(LinkedQueueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(LinkedQueueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(LinkedQueueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new LinkedQueueFrame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonjPanel;
    private javax.swing.JToggleButton ExitjToggleButton4;
    private javax.swing.JToggleButton Q1jToggleButton;
    private javax.swing.JToggleButton Q2jToggleButton;
    private javax.swing.JToggleButton Q3jToggleButton;
    private javax.swing.JLabel enterWordLabel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JTextField inputjTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JPanel outputjPanel;
    // End of variables declaration//GEN-END:variables
}
